name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config user.name asurance
          git config user.email 784672616@qq.com
          npm run deploy
          git push origin gh-pages

