name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          npm run deploy
          git config user.name ${{github.actor}}
          if git diff --exit-code;then echo "there's nothing to commit";else git add -A;git commit -am "auto commit";git pull --rebase;git push origin master;fi

